#!/usr/bin/python

'''
project_euler.net
problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
'''


def solve(max):
    sum = 0
    val = 0
    fib1 = 0
    fib2 = 1
    while val <= max:
        val = fib1 + fib2
        if val % 2 == 0:
            sum = sum + val
        fib1 = fib2
        fib2 = val
    return sum

n = 4000000
print solve(n)
